<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$order = $block->getInfo()->getOrder();
$paymentTitle = $block->getMethod()->getConfigData('title', $order->getStoreId());
?>
<div class="payu method-title">
	<span><?= $block->escapeHtml($paymentTitle) ?></span>
	<img src="<?= $block->getViewFileUrl('Eloom_PayU/images/logo.png'); ?>">
</div>
<table class="data-table admin__table-secondary payu payment__info">
	<tr>
		<th><?= __('Transaction State') ?></th>
		<td>
			<?= $block->getTransactionState() ?>
		</td>
	</tr>
	<tr>
		<th><?= __('PayU Order ID') ?></th>
		<td><?= $block->getOrderId() ?></td>
	</tr>
	<tr>
		<th><?= __('PayU Transaction ID') ?></th>
		<td><?= $block->getTransactionId() ?></td>
	</tr>

	<?php if($ccType = $block->getCcType()):?>
		<tr>
			<th><?= __('Credit Card Type') ?></th>
			<td class="cc-type"><?= $ccType; ?></td>
		</tr>
	<?php endif;?>
	<?php if($lastFour = $block->getCcLast4()):?>
		<tr>
			<th><?= __('Last Credit Card Number') ?></th>
			<td class="cc-last-4"><?= $lastFour; ?></td>
		</tr>
	<?php endif;?>
	<?php if($installments = $block->getInstallments()):?>
		<tr>
			<th><?= __('Installments') ?></th>
			<td class="$installments"><?= $installments; ?></td>
		</tr>
	<?php endif;?>
	<?php if($expirationDate = $block->getExpirationDate()):
			$date = new \DateTime();
			$date->setTimestamp(substr($expirationDate, 0, 10));
      ?>
		<tr>
			<th><?= __('Expiration Date') ?></th>
			<td class="expiration-date"><?= $date->format('d-m-Y H:i:s') ?></td>
		</tr>
	<?php endif;?>
	<?php if($qrCodeEmv = $block->getQrCodeEmv()):?>
      <tr>
          <th><?= __('PIX') ?></th>
          <td>
			<?php if($qrCodeImageBase64 = $block->getQrCodeImageBase64()):?>
                <div class="qr-code-image-base64">
                  <?="<img width='200px' src='data:image/jpeg;base64,$qrCodeImageBase64'/>"?>
                </div>
            <?php endif;?>
              <div class="qr-code-emv">
                  <div><?= $qrCodeEmv ?></div>
                  <div style="display: inline-block;">
                      <svg style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0; width: 20px" aria-hidden="true"
                           focusable="false" data-prefix="fas" data-icon="copy" class="svg-inline--fa fa-copy fa-w-14" role="img"
                           xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                          <path fill="blue"
                                d="M320 448v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24V120c0-13.255 10.745-24 24-24h72v296c0 30.879 25.121 56 56 56h168zm0-344V0H152c-13.255 0-24 10.745-24 24v368c0 13.255 10.745 24 24 24h272c13.255 0 24-10.745 24-24V128H344c-13.2 0-24-10.8-24-24zm120.971-31.029L375.029 7.029A24 24 0 0 0 358.059 0H352v96h96v-6.059a24 24 0 0 0-7.029-16.97z">
                          </path>
                      </svg>
                      <a id="payu_pix_copy" style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0;"><?= __('Copy PIX code') ?></a>
                      <input style="opacity: 0; user-select: none; pointer-events: none;" type="text" value="<?= $qrCodeEmv ?>" id="payu_pix_qr_code"/>
                  </div>
              </div>
          </td>
      </tr>
	<?php endif;?>
	<?php if($barCode = $block->getBarCode()):?>
      <tr>
          <th><?= __('Bar Code') ?></th>
          <td class="boleto-barcode"><?= $barCode; ?></td>
      </tr>
	<?php endif;?>
	<?php if($link = $block->getPaymentLink()):?>
		<tr>
			<th><?= __('Voucher Link') ?></th>
			<td class="boleto-link">
				<a class="action-default" href="<?= $link; ?>" target="_blank" title="<?= __('Open') ?>">
					<?= __('Open') ?>
					<img src="<?php echo $block->getViewFileUrl('Eloom_PayU/images/barcode.svg'); ?>"/>
				</a>
			</td>
		</tr>
	<?php endif;?>
	<?php if($link = $block->getPdfLink()):?>
		<tr>
			<th><?= __('Voucher PDF') ?></th>
			<td class="boleto-pdf">
				<a class="action-default" href="<?= $link; ?>" target="_blank" title="<?= __('Print') ?>">
					<?= __('Print') ?>
					<img src="<?php echo $block->getViewFileUrl('Eloom_PayU/images/print.svg'); ?>"/>
				</a>
			</td>
		</tr>
	<?php endif;?>
	<?php if($link = $block->getBankUrl()):?>
		<tr>
			<th><?= __('Bank') ?></th>
			<td class="bank-url">
				<a class="action-default" href="<?= $link; ?>" title="<?= __('Bank Action') ?>">
					<?= __('Bank Action') ?>
				</a>
			</td>
		</tr>
	<?php endif;?>
</table>

<?php if ($specificInfo) : ?>
	<table class="data-table admin__table-secondary payu payment__info especific">
		<?php foreach ($specificInfo as $label => $value) : ?>
			<tr>
				<th><?= $block->escapeHtml($label) ?></th>
				<td>
					<?= nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
<?php endif; ?>

<?= $block->getChildHtml() ?>

<script>
	require([
		'jquery'
	], function ($) {
		$(document).ready(function () {
			try {
				$('#payu_pix_copy').click(function () {
					var copyText = document.getElementById('payu_pix_qr_code');

					copyText.select();
					copyText.setSelectionRange(0, 99999);
					document.execCommand("copy");

					alert("<?= __('PIX code copied')?>");
				});
			} catch (e) {
				console.error(e);
			}
		});
	});
</script>
