define("jquery underscore ko mage/storage Eloom_Payment/js/cards Eloom_Payment/js/payform Eloom_Core/js/model/url-builder Magento_Payment/js/model/credit-card-validation/credit-card-data Magento_Checkout/js/model/quote Magento_Checkout/js/model/full-screen-loader Magento_Checkout/js/checkout-data Magento_Checkout/js/action/get-totals Magento_Vault/js/view/payment/vault-enabler Eloom_PayU/js/view/checkout/fingerprint".split(" "),function(d,g,n,h,q,e,k,v,p,m,w,r,t,u){return q.extend({defaults:{template:"Eloom_PayU/payment/cc-form",
code:"eloom_payments_payu_cc"},rootPaymentCode:"eloom_payments_payu",totals:n.observable(window.checkoutConfig.totalsData),banksOfMexico:n.observableArray(),initialize:function(){var a=this;this._super();p.paymentMethod.subscribe(function(){a.clearCreditCardInfo();a.reloadTotals()},null,"change");p.shippingMethod.subscribe(function(){a.clearCreditCardInfo();a.reloadTotals()},null,"change");this.vaultEnabler=new t;this.vaultEnabler.setPaymentCode(this.getVaultCode(this.getCode()));this._initialize();
return a},_initialize:function(){payU.setLanguage(window.checkoutConfig.payment[this.rootPaymentCode].language);payU.setURL(window.checkoutConfig.payment[this.getCode()].url.payments);payU.setPublicKey(window.checkoutConfig.payment[this.getCode()].publicKey);payU.setAccountID(window.checkoutConfig.payment[this.getCode()].accountId);this.monthsWithoutInterestActive=window.checkoutConfig.payment[this.getCode()].monthsWithoutInterestActive},clearCreditCardInfo:function(){this.creditCardNumber("");this.creditCardBrand("");
this.creditCardBrandIcon("");this.creditCardExpiry("");this.creditCardCvv("");this.installments.removeAll()},initObservable:function(){this._super().observe(["injectPaymentBehavior"]);return this},isActive:function(){return!0},injectPaymentBehavior:function(){var a=document.getElementById(this.getCode().concat("_number")),b=document.getElementById(this.getCode().concat("_expiry")),c=document.getElementById(this.getCode().concat("_cvv"));e.cardNumberInput(a);e.expiryInput(b);e.cvcInput(c)},reloadTotals:function(){var a=
d("#".concat(this.getCode()).concat("_installments")).val();m.startLoader();h.post(k.createUrl("/eloom/payu/totals",{}),JSON.stringify({paymentMethod:{method:this.getCode(),additional_data:{installments:a?a:0}},shippingAmount:this.getShippingAmount()}),!1).done(function(b){b=d.Deferred();r([],b);d.when(b).done(function(){m.stopLoader()})}).fail().always(function(){m.stopLoader()})},isShowCreditCardBrandIcon:function(){return window.checkoutConfig.payment[this.getCode()].icons.show},isInSandboxMode:function(){return window.checkoutConfig.payment[this.rootPaymentCode].isInSandboxMode},
isTransactionInTestMode:function(){return window.checkoutConfig.payment[this.rootPaymentCode].isTransactionInTestMode},creditCardNumberStatusListen:function(a){var b=this.status.INITIAL;if(a){var c=e.parseCardType(a),f=a.match(/[0-9]+/g).join([]).length;c?(this.creditCardBrand(c),-1<e.lengthFromType(c).indexOf(l)&&(b=e.validateCardNumber(a)?this.status.SUCCESS:this.status.ERROR)):5<f&&(this.creditCardBrand(""),b=this.status.ERROR);this.isShowCreditCardBrandIcon()&&(a=window.checkoutConfig.payment[this.getCode()].icons.brands[this.creditCardBrand()],
void 0!==a&&this.creditCardBrandIcon(a))}this.creditCardNumberStatus(b)},getData:function(){var a=d("#".concat(this.getCode()).concat("_bank")).val(),b=d("#".concat(this.getCode()).concat("_installments")).val();a={method:this.item.method,additional_data:{cc_number:this.creditCardNumber(),cc_type:this.creditCardBrand(),cc_expiry:this.creditCardExpiry(),cc_cvv:this.creditCardCvv(),cc_owner:d("#".concat(this.getCode()).concat("_owner")).val(),cc_installments:b?b:0,cc_bank:a?a:"null",cc_device_session_id:u.getDeviceSessionId(),
grand_total:this.getTotalOrderAmount()}};a.additional_data=g.extend(a.additional_data,this.additionalData);this.vaultEnabler.visitAdditionalData(a);return a},isVaultEnabled:function(){return this.vaultEnabler.isVaultEnabled()},isShowBanksForMexico:function(){var a=this,b=a.creditCardBrand();(b="es_MX"==window.eloom.core.lang&&this.monthsWithoutInterestActive&&("mastercard"==b||"visa"==b))&&h.post(k.createUrl("/eloom/payu/banks",{}),null,!1).done(function(c){c=JSON.parse(c);a.banksOfMexico.removeAll();
c.data&&g.each(c.data,function(f,x){f&&a.banksOfMexico.push({v:f.value,t:f.label})})});return b},getLogoUrl:function(){return window.checkoutConfig.payment[this.rootPaymentCode].url.logo},creditCardNumberBlurEvent:function(){this.creditCardNumber()&&(this.creditCardNumberStatusListen(),this.installmentsListen())},installmentsListen:function(){var a=this;a.installments.removeAll();h.post(k.createUrl("/eloom/payu/pricing",{}),JSON.stringify({shippingAmount:a.getShippingAmount()}),!1).done(function(b){b=
JSON.parse(b);b.data&&g.each(b.data,function(c,f){c&&a.installments.push({v:c.value,t:c.label})})})},isPlaceOrderEnabled:function(){return this.creditCardNumber()&&this.creditCardBrand()&&this.creditCardExpiry()&&this.creditCardCvv()?this.getCode()==this.isChecked():!1}})});
