<?php
/**
 * @var \Eloom\PayU\Block\Adminhtml\Config\Fieldset\Hint $block
 */
$helpLink = $block->escapeUrl($block->getHelpLink());
?>
<?php if ($helpLink) : ?>
    <div class="eloom-payu-payment-notice">
        <?= $block->escapeHtml(__('Not sure what PayU payment method to use? Click ')) ?>
        <a href="<?php echo $helpLink; ?>" target="_blank"><?= $block->escapeHtml(__('here')) ?></a>
        <?= $block->escapeHtml(__(' to learn more.')) ?>
    </div>
<?php endif; ?>